const FETCH_FORMS = {
    LOAD : "FORMS_LOAD",
    LOAD_SUCCESS : "FORMS_LOAD_SUCCESS",
    LOAD_FAIL : "FORMS_LOAD_FAIL"
}

const CREATE_FORM = {
    LOAD : "CREATE_FORM_LOAD",
    LOAD_SUCCESS : "CREATE_FORM_SUCCESS",
    LOAD_FAIL : "CREATE_FORM_FAIL"
}

export { FETCH_FORMS, CREATE_FORM }